version: '3.9'

services:
  db:
    image: postgres:14.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carproject
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8077:8080
